@startuml

skinparam usecase {
  FontName Ricty Diminished
}

title kokoユースケース
left to right direction

note bottom of (ユーザ) : Twitterアプリ\nからアクセス
actor :ユーザ:
note top of (管理者) : Webインターフェイス\nからアクセス
actor :管理者:
usecase Twitter

rectangle "koko" {
  :ユーザ: -- (フォローする)
  :ユーザ: -- (会話する)
  (フォローする) ..> (ビジネスロジック) : <<依存>>
  (会話する) ..> (ビジネスロジック) : <<依存>>
  (ビジネスロジック) ..> (機能設定) : <<依存>>
  (ビジネスロジック) ..> Twitter : <<依存>>

  (機能設定) -- :管理者:
}

@enduml
